variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    --no-snapshot-updates

stages:
  - backend
  - frontend

cache:
  key: "maven-$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository/

backend:
  stage: backend
  image: gitlab-edu.supsi.ch:5050/dti-isin/labingsw/common:maven3java17
  before_script:
    - cd backend
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS clean install'
  after_script:
    - cd ..
  artifacts:
    paths:
      - backend/target/fscli-backend.jar
      - .m2/repository/ch/supsi/fscli/
    expire_in: 1 hour

frontend:
  stage: frontend
  dependencies:
    - backend
  image: gitlab-edu.supsi.ch:5050/dti-isin/labingsw/common:maven3java17
  before_script:
    - 'cd frontend'
    - 'Xvfb :99 -screen 0 1920x1080x16 &'
  script:
    - 'DISPLAY=:99 mvn $MAVEN_OPTS $MAVEN_CLI_OPTS -Dheadless clean package'
  after_script:
    - cd ..
  artifacts:
    paths:
      - frontend/target/fscli-jar-with-dependencies.jar
    expire_in: 1 hour